import type { Metadata } from 'next';

import '@/styles/globals.css';
import Providers from '@/utils/query/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <div className='max-w-content min-h-dvh max-h-dvh my-0 mx-auto'>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
